services:
  ros_caric:
    image: ros_caric
    container_name: ros_caric_container
    build:
      context: .
      dockerfile: Dockerfile
    command: >
          bash -c "sleep infinity"
    #   bash -c "apt-get update && 
    #   cd /root/ws_caric &&       
    #   rosdep install --from-paths src --ignore-src -r -y && 
    #   touch /root/ws_caric/src/rotors_simulator/rotors_hil_interface/CATKIN_IGNORE &&
    #   source /opt/ros/noetic/setup.bash && catkin build traj_gennav &&
    #   catkin build && sleep infinity"
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    deploy:
      # let it use the GPU
      resources:
        reservations:
          devices:
            - driver: nvidia # https://stackoverflow.com/a/70761193
              count: 1
              capabilities: [ gpu ]   
    volumes:
      # display stuff
      - $HOME/.Xauthority:/root/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix
      # developer stuff
      # - .dev:/root/.dev:rw # developer config
      # - .bashrc:/root/.bashrc:rw # bash config
      - /var/run/docker.sock:/var/run/docker.sock # access docker API for container name    
      - ./ws_caric:/root/ws_caric:rw  # Mount your local src directory
    # runtime: nvidia
    privileged: true
    stdin_open: true
    tty: true